[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
study_dao_vault = "ExY4RXQaD86GyNpofZy9PJV32QKPaDRnzcvByLDb8bTZ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
